In [1]:
import chardet

In [2]:
import pandas as pd
pd.set_option('display.max_rows', 100)

In [3]:
with open('20220504-1180147058-umsatz.CSV', 'rb') as f:
    enc = chardet.detect(f.read())  # or readline if the file is large

print(enc)
#df = pd.read_csv('20220504-1180147058-umsatz.CSV',  encoding = enc['encoding'])

{'encoding': 'ISO-8859-1', 'confidence': 0.73, 'language': ''}

In [21]:
df_ = pd.read_csv('buchung_01_05_03_06.CSV',  encoding = 'UTF-8',on_bad_lines='skip', delimiter=',')

In [24]:
df_[['Amt', 'Category']]

         Amt                                       Category
0       3.95                      Konsumkosten:Kontoführung
1     100.00              Sparrate:Prämiensparen Jörg+Karin
2     237.05                                            NaN
3     913.88                                            NaN
4     111.56                   Altersvorsorge:Postbank Jörg
..       ...                                            ...
101    24.94                                            NaN
102   425.98  Laufende Kosten:Haushalt (Kleinanschaffungen)
103    39.90                       Konsumkosten:Ems-Zeitung
104    24.00                      Einnahmen:Kindergeld Till
105  1500.00                                      Umbuchung

[106 rows x 2 columns]

In [19]:
df_sk = pd.read_csv('20220504-1180147058-umsatz.CSV',  encoding = 'ISO-8859-1',on_bad_lines='skip', delimiter=';')

In [5]:
df_sk = df_sk[['Beguenstigter/Zahlungspflichtiger', 'Betrag']]

In [6]:
pd.options.display.max_rows

100

In [7]:
import pandas as pd
pd.set_option('display.max_colwidth', None)

In [8]:
display(df_sk)

,Beguenstigter/Zahlungspflichtiger,Betrag
0,AMAZON PAYMENTS EUROPE S.C.A.,"-11,90"
1,AMAZON PAYMENTS EUROPE S.C.A.,"-69,99"
2,VATTENFALL EUROPE SALES UEBERSEERING 12,"-166,00"
3,AMAZON PAYMENTS EUROPE S.C.A.,"-19,93"
4,Ludgerusschule Kontoinh. Land Niedersachsen,"-18,00"
5,AMAZON PAYMENTS EUROPE S.C.A.,"-15,90"
6,Neue Osnabruecker Zeitung Grosse Str. 17 - 19,"-37,90"
7,Combi Verbrauchermarkt SAGT DANKE. FI110002 GIR 69170897//ASCHENDOR/DE,"-54,78"
8,LIDL DIENSTLEISTUNG GMBH UND CO KG//Aschendorf/DE,"-91,68"
9,Musikschule Papenburg,"-32,00"
10,WERTGARANTIE SE,"-16,00"
11,WERTGARANTIE SE,"-16,00"
12,BASLER SACHVERS.-AG,"-38,89"
13,Wasserverband Huemmling,"-43,00"
14,Dr. Joerg und Karin Wingbermuehle,"-100,00"
15,LBS Norddeutsche Landesbausparkass e Berlin-Hannover,"-43,00"
16,Allianz Lebensvers. AG,"-350,00"
17,SANTANDER CONSUMER BANK AG,"-187,00"
18,"Heidelberger Lebensversicherung AG Im Breitspiel 2-4, 69126 Heidelberg","-214,37"
19,"Heidelberger Lebensversicherung AG Im Breitspiel 2-4, 69126 Heidelberg","-234,21"
20,OEffentliche Lebensversicherungsanstalt Oldenburg,"-83,03"
21,STANDARD LIFE VERSICHERUNG ZW DEUTSCHLAND DER STANDARD LIFE Lyoner Str. 15,"-141,64"
22,STANDARD LIFE VERSICHERUNG ZW DEUTSCHLAND DER STANDARD LIFE Lyoner Str. 15,"-164,01"
23,BASLER LV AG,"-86,34"
24,PayPal Europe S.a.r.l. et Cie S.C.A,"-61,76"
25,UNION KRANKENVERSICHERUNG AKTIENGESELLSCHAFT,"-10,38"
26,PB Lebensversicherung AG ProActiv-Platz 1,"-111,56"
27,DSL Bank Ndl DB AG Friedrich-Ebert-Allee 114-126,"-913,88"
28,Entis Lebensversicherung AG Augustaanlage 65,"-237,05"
29,Joerg Wilhelm Wingbermuehle Karin Maria Wingbermuehle,"-100,00"
30,NaN,"-3,95"
31,Niedersaechsische Landeshauptkasse,"4018,56"
32,BHW Bausparkasse AG Lubahnstr. 2,"-85,00"
33,SPIEL UND SPORT RHEDE E.V.,"-36,00"
34,ROSEN TECHNOLOGY AND Lingen,"1924,61"
35,Klaas+Kock Fil.219//Rhede/DE,"-19,73"
36,Telekom Deutschland GmbH Landgrabenweg 151 53227 Bonn DE,"-54,94"
37,C+A//Papenburg/DE,"-71,94"
38,AVIA Gottschald - Pickel//Rhede/DE,"-56,00"
39,PayPal Europe S.a.r.l. et Cie S.C.A,"-34,98"
40,PayPal Europe S.a.r.l. et Cie S.C.A,"-27,84"
41,Combi Verbrauchermarkt SAGT DANKE. FI110002 GIR 69170897//ASCHENDOR/DE,"-106,08"
42,LIDL DIENSTLEISTUNG GMBH UND CO KG//Aschendorf/DE,"-85,11"

In [9]:
df_own = pd.read_csv('detail2022_reduced.csv', on_bad_lines='skip', delimiter=';')
df_own['abgebucht'] = 'Nein'

In [10]:
df_own

                        Posten    Betrag abgebucht
0        Hauskredit - DSL-Bank  913,88 €      Nein
1                          BHW   85,00 €      Nein
2       Autokredit - Santander  187,00 €      Nein
3           Vattenfall - Strom  166,00 €      Nein
4             Vattenfall - Gas  148,00 €      Nein
5       Wasserverband Hümmling   43,00 €      Nein
6         Heidelberger 7934-03  234,21 €      Nein
7         Heidelberger 7934-02  214,37 €      Nein
8        Standard Life - Karin  141,64 €      Nein
9         Standard Life - Jörg  164,01 €      Nein
10                  UKV - Jörg   10,38 €      Nein
11              Unfall - Karin   38,89 €      Nein
12                  LV - Karin   86,34 €      Nein
13                  BU - Karin   83,03 €      Nein
14              Allianz - Jörg  175,00 €      Nein
15             Allianz - Karin  175,00 €      Nein
16                ENTIS - Jörg  237,05 €      Nein
17             Postbank - Jörg  111,56 €      Nein
18              Ludgerusschule   50,00 €      Nein
19       Musikschule Papenburg   32,00 €      Nein
20        Prämiensparen - Till   25,00 €      Nein
21           Fondsparen - Till  100,00 €      Nein
22                Amazon Prime    7,99 €      Nein
23             Congstar - Jörg   15,00 €      Nein
24                  Emszeitung   39,90 €      Nein
25                         GEZ    0,00 €      Nein
26                         HD+    6,00 €      Nein
27                Kontoführung    5,00 €      Nein
28                      Readly    9,95 €      Nein
29                         Sky   36,36 €      Nein
30                     Spotify   14,99 €      Nein
31                     Telekom   54,94 €      Nein
32                  TV Digital    0,00 €      Nein
33            Vodafone - Karin   15,00 €      Nein
34                Wertgarantie   32,00 €      Nein
35     Baussparvertrag - Karin   43,00 €      Nein
36  Prämiensparen Karin - Jörg  100,00 €      Nein

In [ ]:
# search_str = ""
# title_string = ''
# #df_2[df_2['PS1'].str.contains(substr)]
# df_my_db[df_my_db['PS1'].str.contains(ps_str) & df_my_db['Title'].str.contains(title_string)]

In [14]:
# Implement Python Switch Case Statement using Class

class CorrelateStrings:

    def switch(self, chose_posten):
        default = "Nicht vorhanden"
        return getattr(self, 'case_' + str(chose_posten), lambda: default)()
    
    def case_hauskredit_dsl_bank(self):
        return "DSL Bank Ndl DB AG Friedrich-Ebert-Allee 114-126"
    
    def case_bhw(self):
        return "BHW Bausparkasse AG Lubahnstr. 2"
    
    def case_autokredit_santander(self):
        return "SANTANDER CONSUMER BANK AG"
    
    def case_vattenfall_strom(self):
        return "VATTENFALL EUROPE SALES UEBERSEERING 12"
    
    def case_vattenfall_gas(self):
        return "VATTENFALL EUROPE SALES UEBERSEERING 12"
    
    def case_wasserverbandhümmling(self):
        return "Wasserverband Huemmling"
    
    def case_heidelberger7934_03(self):
        return "Heidelberger Lebensversicherung AG Im Breitspiel 2-4, 69126 Heidelberg"
    
    def case_heidelberger7934_02(self):
        return "Heidelberger Lebensversicherung AG Im Breitspiel 2-4, 69126 Heidelberg"
    
    def case_standardlife_karin(self):
        return "STANDARD LIFE VERSICHERUNG ZW DEUTSCHLAND DER STANDARD LIFE Lyoner Str. 15"
    
    def case_standardlife_joerg(self):
        return "STANDARD LIFE VERSICHERUNG ZW DEUTSCHLAND DER STANDARD LIFE Lyoner Str. 15"
    
    def case_ukv_jörg(self):
        return "UNION KRANKENVERSICHERUNG AKTIENGESELLSCHAFT"
    
    def case_unfall_karin(self):
        return "BASLER SACHVERS.-AG"
    
    def case_lv_karin(self):
        return "BASLER LV AG"
    
    def case_bu_karin(self):
        return "OEffentliche Lebensversicherungsanstalt Oldenburg"
    
    def case_allianz_jörg(self):
        return "Allianz Lebensvers. AG"
    
    def case_allianz_karin(self):
        return "Allianz Lebensvers. AG"
    
    def case_entis_jörg(self):
        return "Entis Lebensversicherung AG Augustaanlage 65"
    
    def case_postbank_jörg(self):
        return "PB Lebensversicherung AG ProActiv-Platz 1"
    
    def case_ludgerusschule(self):
        return "Ludgerusschule Kontoinh. Land Niedersachsen"
    
    def case_musikschulepapenburg(self):
        return "Musikschule Papenburg"
    
    def case_prämiensparen(self):
        return "Sparrate 4585375738"
    
    def case_fondsparen_till(self):
        return "7717096 VERMOEGENSDEPOT SAMMELBUCHUNG SPARPLAN WKN A0M430, 986855, A0MN91 A0X754, A0M003"
    
    def case_amazonprime(self):
        return "amazonprime"
    
    def case_congstar_jörg(self):
        return "congstar - eine Marke der Telekom Deutschland GmbH"

    def case_emszeitung(self):
        return "Neue Osnabruecker Zeitung Grosse Str. 17 - 19"
    
    def case_gez(self):
        return "Rundfunk 11.2019 - 01.2020 Beitragsnr. 557504448"
    
    def case_hdplus(self):
        return ""
    
    def case_kontoführung(self):
        return ""
    
    def case_readly(self):
        return ""
    
    def case_sky(self):
        return "Sky Deutschland Fernsehen GmbH Co. KG"
    
    def case_spotify(self):
        return ""
    
    def case_telekom(self):
        return "Telekom Deutschland GmbH Landgrabenweg 151 53227 Bonn DE"
    
    def case_tvdigital(self):
        return "FUNKE TV Guide GmbH"
    
    def case_vodafone_karin(self):
        return "HB-Handy-Laden TAN 995845"
    
    def case_wertgarantie(self):
        return "WERTGARANTIE SE"
    
    def case_baussparvertrag_karin(self):
        return "LBS Norddeutsche Landesbausparkass e Berlin-Hannover"
    
    def case_prämiensparenkarin_jörg(self):
        return "Joerg Wilhelm Wingbermuehle Karin Maria Wingbermuehle"
    
    
    #====
    
    def case_1(self):
        return "Monday"
 
    def case_2(self):
        return "Tuesday"
 
    def case_emszeitung(self):
        return "ﬁ9"
    
    
    
   
#     def case_vattenfall_strom(self):
#         return "

#s = CorrelateStrings()

#print(s.switch('Emszeitung'))
#print(s.switch(0))

In [15]:
s = CorrelateStrings()
for lfi, lf in df_own.iterrows():
    posten_tmp = df_own.loc[lfi, 'Posten'].lower().replace(' ','').replace('-','_') 
    
    print('posten_tmp: ', posten_tmp)
    if s.switch(posten_tmp) != "Nicht vorhanden":
        print(lfi)
        df_own.loc[lfi, 'abgebucht'] = "Ja"
        
    #print('==')

posten_tmp:  hauskredit_dsl_bank
0
posten_tmp:  bhw
1
posten_tmp:  autokredit_santander
2
posten_tmp:  vattenfall_strom
3
posten_tmp:  vattenfall_gas
4
posten_tmp:  wasserverbandhümmling
5
posten_tmp:  heidelberger7934_03
6
posten_tmp:  heidelberger7934_02
7
posten_tmp:  standardlife_karin
8
posten_tmp:  standardlife_jörg
posten_tmp:  ukv_jörg
10
posten_tmp:  unfall_karin
11
posten_tmp:  lv_karin
12
posten_tmp:  bu_karin
13
posten_tmp:  allianz_jörg
14
posten_tmp:  allianz_karin
15
posten_tmp:  entis_jörg
16
posten_tmp:  postbank_jörg
17
posten_tmp:  ludgerusschule
18
posten_tmp:  musikschulepapenburg
19
posten_tmp:  prämiensparen_till
posten_tmp:  fondsparen_till
21
posten_tmp:  amazonprime
22
posten_tmp:  congstar_jörg
23
posten_tmp:  emszeitung
24
posten_tmp:  gez
25
posten_tmp:  hd+
posten_tmp:  kontoführung
27
posten_tmp:  readly
28
posten_tmp:  sky
29
posten_tmp:  spotify
30
posten_tmp:  telekom
31
posten_tmp:  tvdigital
32
posten_tmp:  vodafone_karin
33
posten_tmp:  wertgarantie
34
posten_tmp:  baussparvertrag_karin
35
posten_tmp:  prämiensparenkarin_jörg
36

In [24]:
df_own

                        Posten    Betrag abgebucht
0        Hauskredit - DSL-Bank  913,88 €        Ja
1                          BHW   85,00 €        Ja
2       Autokredit - Santander  187,00 €        Ja
3           Vattenfall - Strom  166,00 €        Ja
4             Vattenfall - Gas  148,00 €        Ja
5       Wasserverband Hümmling   43,00 €        Ja
6         Heidelberger 7934-03  234,21 €        Ja
7         Heidelberger 7934-02  214,37 €        Ja
8        Standard Life - Karin  141,64 €      Nein
9         Standard Life - Jörg  164,01 €      Nein
10                  UKV - Jörg   10,38 €      Nein
11              Unfall - Karin   38,89 €      Nein
12                  LV - Karin   86,34 €      Nein
13                  BU - Karin   83,03 €      Nein
14              Allianz - Jörg  175,00 €      Nein
15             Allianz - Karin  175,00 €      Nein
16                ENTIS - Jörg  237,05 €      Nein
17             Postbank - Jörg  111,56 €      Nein
18              Ludgerusschule   50,00 €      Nein
19       Musikschule Papenburg   32,00 €      Nein
20        Prämiensparen - Till   25,00 €      Nein
21           Fondsparen - Till  100,00 €      Nein
22                Amazon Prime    7,99 €      Nein
23             Congstar - Jörg   15,00 €      Nein
24                  Emszeitung   39,90 €        Ja
25                         GEZ    0,00 €      Nein
26                         HD+    6,00 €      Nein
27                Kontoführung    5,00 €      Nein
28                      Readly    9,95 €      Nein
29                         Sky   36,36 €      Nein
30                     Spotify   14,99 €      Nein
31                     Telekom   54,94 €      Nein
32                  TV Digital    0,00 €      Nein
33            Vodafone - Karin   15,00 €      Nein
34                Wertgarantie   32,00 €      Nein
35     Baussparvertrag - Karin   43,00 €      Nein
36  Prämiensparen Karin - Jörg  100,00 €      Nein